# TallyIO Security and License Configuration for cargo-deny

[graph]
# Ensure all dependencies are properly resolved
all-features = true
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
]

[advisories]
# Security vulnerability database
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"
ignore = [
    # Add specific advisories to ignore if needed
    # "RUSTSEC-YYYY-NNNN",
]

[licenses]
# License compliance for TallyIO
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
]
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
    "MPL-2.0",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[[licenses.exceptions]]
# Allow specific crates with different licenses if needed
# name = "crate-name"
# allow = ["license"]

[bans]
# Banned crates and features
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = [
    # Deny unsafe or problematic crates
    { name = "openssl", version = "*" },  # Use rustls instead
    { name = "native-tls", version = "*" },  # Use rustls instead
]
skip = []
skip-tree = []

[sources]
# Allowed sources for dependencies
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    # Allow specific git repositories if needed
    # "https://github.com/user/repo",
]
